# Generated by Django 5.1.7 on 2025-03-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='search_query',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['search_query'], name='videos_vide_search__354e1f_idx'),
        ),
    ]
